name: EnderchestDeathDrop
main: com.hackthedoc.enderchestdeathdrop.Plugin
version: 0.0.1
api-version: 1.21
permissions:
  enderchestdeathdrop.bypass:
    description: "Allow players to bypass the drop of their enderchest at their death"
    default: false